#===========================================================================
#
# Toplevel makefile. Recurses into build directories.
#
# License  : GPL (General Public License)
# Author   : Arend Lammertink <lamare AT gmail DOT com>
# Date     : 2016/05/18 (version 0.1)
#
#===========================================================================

SUBDIRS = config

#---------------------------------------------------------------------------
# Include the dirty details aka implementation.
#---------------------------------------------------------------------------
include LaMake/recurse.mk     # LaMake should be installed in or linked from
                              # /usr[/local]/include
#===========================================================================
